#+OPTIONS: toc:nil
#+TITLE: CSE 361 HW-0

* 1.2-1

Give an example of an application that requires algorithmic content at
the application level, and discuss the function of the algorithms
involved.


An application that manages students for a classroom might require
algorithmic content at the application level. It could use a sorting
algorithm to sort students alphabetically by name for attendance, or a
random shuffling algorithm in order to assign random seats to the
students in the class.

* 1.2-2

Suppose we are comparing implementations of insertion sort and merge
sort on the same machine. For inputs of size n, insertion sort runs in
$8n^2$ steps, while merge sort runs in $64 n \lg n$ steps. For which
values of n does insertion sort beat merge sort?


Insertion sort beats merge sort when $2 <= n <= 6$ (where n is an
integer)

* 1.2-3

3 What is the smallest value of n such that an algorithm whose running
time is $100n^2$ runs faster than an algorithm whose running time is
$2^n$ on the same machine?

 
Assuming n can ony be an integer, the smallest value of n where
$100n^2$ is faster than $2^n$ is 15.

* Table of values

|         | 1 second | 1 minute |    1 hour |      1 day |     1 month |     1 year |   1 century |
|---------+----------+----------+-----------+------------+-------------+------------+-------------|
| lg(n)   |  e^{1e6} | e^{60e6} | e^{3.6e9} | e^{86.4e9} | e^{2.59e12} | e^{946e12} | e^{94.6e15} |
| sqrt(n) |     1e12 |   3.6e15 |   12.0e18 |    7.46e21 |     6.72e24 |     895e27 |     8.95e33 |
| n       |      1e6 |     60e6 |    3.60e9 |     86.4e9 |     2.59e12 |     946e12 |     94.6e15 |
| n lg n  |   87.8e3 |   3.95e6 |     189e6 |     3.91e9 |       102e9 |    30.5e12 |     2.66e15 |
| n^2     |     1000 |     7746 |      60e3 |      294e3 |      1.61e6 |     30.7e6 |       307e6 |
| n^3     |      100 |      391 |      1532 |       4420 |       13700 |       98e3 |       455e3 |
| 2^n     |       19 |       25 |        31 |         36 |          41 |         49 |          56 |
| n!      |        9 |       11 |        12 |         14 |          15 |         17 |          18 |
