* Principle of utility

If an act or rule is right it will bring about the greatest pleasure
for the greatest number of people.

* Rule/Indirect utilitarianism

Follow the rules. A rule is a good rule if it generally brings the
greatest amount of pleasure for the greatest number of people


* Bentham vs Mill

Bentham believed that you should do whatever brings you the most
pleasure.

Mill believed that you should do whatever brings the most pleasure to
the greatest number of people.

* Psychological vs Ethical Egoism

Psychological Egoism holds that a person _will_ do whatever is best
for themselves.

Ethical Egoism holds that a person _should_ do whatever is best for
themselves.

* Telos of a human being

Rationality/Happiness

* Rights in the state of nature according to Hobbes

A person has the right to do whatever is necessary to preserve one's
own life.

* Prisoner's Dilemma

Attack neighbor or don't.

Rat on cellmate or don't.

* Subjective theory of value

An act only has value because we perceive it to have value based on
our own wants. Nothing has any intrinsic value.

* Categorical Imperative

** Part 1

Act in such a way that the maxim of your action could become universal
law.

This is a problem because some things could be willed to become
universal law that are generally considered bad.

** Part 2

Treat every human being as an end in himself and not just a means to
your own end

* Theological Ethics

It is a problem if god arbitrarily decides what is good and bad
because there is no way to know what to do in any situation not
covered by something god has said.

It is a problem if god has a reason for what is good and bad because
then he is cut out of the equation. You could simply follow the same
philosophy god follows without having god in the mix.

* Autonomous/Heteronomous will

Autonomous will is "self law" - Being controlled wholly by your own
thoughts and desires

Heteronomous will is "other law" - Being controlled by outside forces

* Kant vs Utilitarian

In some situations a utilitarian would say it is acceptable to use a
person as a mere means to an end in which pleasure is brought to a
great number of people.

* Utilitarian Promises

If I promise someone I will do something, and they die. It can now
cause them no displeasure for me to keep my promise, therefore I can
break it if it is pleasing to me.

* Moral vs Value theory

Value is a personal belief. "It is wrong to kill people"

Moral is a system of beliefs for deciding between good and bad.

* Inclination and Kant

Kant believes that actions we perform because we are inclined to do so
are not morally praiseworthy.

If I help my mom because I like helping my mom, I did it because I
wanted to, not because I know it is the right thing to do.
